### ISSUE TITLE
[Request] Show Cloudwatch logs of the Lambda in function.json

### ISSUE THREAD

**Issue by jlandowner** [fujiwara/lambroll#10]
Like AWS CLI v2, I would like to watch the Lambda function logs in Cloudwatch logs with a single command such as 'lambroll logs'.

Lambda deployment step has improved by lambroll(I use it for almost all of my functions.) , but it has still some steps to watch these function logs.

Thanks you.

**Comment by fujiwara** [comment]
@jlandowner 
I agree to `lambroll logs` would be useful, but I hope to keep lambroll be simple too.
How do you think about `lambroll logs` invokes `aws logs tail` internal if aws-cli v2 installed?

**Comment by jlandowner** [comment]
I think it's ok to use aws-cli. v2 will be installed in almost all environment for lambroll.

**Comment by fujiwara** [comment]
@jlandowner v0.4.0 released which have logs subcommand. Thank you!
