### ISSUE TITLE
Allow to create an alias to unpublished lambda version

### ISSUE THREAD

**Issue by thara** [fujiwara/lambroll#140]
Currently, lambroll creates an alias to published lambda version only.

https://github.com/fujiwara/lambroll/blob/58d4dcfcba8a2aa3f73b4c627e9afa333f176793/deploy.go#L157-L161

However, AWS allows aliasing to unpublished lambda version such like:

```bash
$ aws lambda create-alias --function-name $func_name --name $alias_name --function-version '$LATEST'
```

I think lambroll should be allow this in the same way.

What do you think about it?

**Comment by fujiwara** [comment]
Thats right. But aliasing to unpublished version breaks backward compatibility.

I plan to add `--alias-to-latest` option for setting alias to $LATEST. How about it?

**Comment by thara** [comment]
@fujiwara (I'm sorry for the late reply)

> Thats right. But aliasing to unpublished version breaks backward compatibility.

Ya, you are absolutely correct.

> I plan to add --alias-to-latest option for setting alias to $LATEST. How about it?

That sounds great!

**Comment by fujiwara** [comment]
@thara v0.11.5 (includes --alias-to-latest) released! 
https://github.com/fujiwara/lambroll/releases/tag/v0.11.5

**Comment by thara** [comment]
@fujiwara It's great job! thx!
