### ISSUE TITLE
lambroll does not respect AWS shared config

### ISSUE THREAD

**Issue by aereal** [fujiwara/lambroll#158]
# expected behavior

Passing either `AWS_REGION` environment variable or no `--region` argument but having `~/.aws/config` that contains `region = ap-northeast-1`, lambroll expected to consume region from `~/.aws/config`.

# actual behavior

The lambroll does not respect region config in `~/.aws/config`:

```
[2021-08-09 12:29:54] ✘╹◡╹✘ < lambroll --profile default init --function-name my-func
2021/08/09 12:29:57 [info] lambroll v0.11.5
2021/08/09 12:29:57 [error] failed to GetFunctionmy-func: MissingRegion: could not find region configuration
```

# solution

The lambroll could consume shared config.

# version info

```
[2021-08-09 12:27:13] ✘╹◡╹✘ < lambroll version
lambroll v0.11.5
```

**Comment by fujiwara** [comment]
Thank you for the reporting!. Released v0.11.6.
