### ISSUE TITLE
Unexpected success messages appear when it tries to deploy the Image runtime function

### ISSUE THREAD

**Issue by moznion** [fujiwara/lambroll#205]
When the existing lambda function is not `Image` runtime (i.e. `packageType` is `Zip`) and it attempts to overwrite that function by `Image` runtime function, `lambroll deploy` command behaves successfully but I deem this is not expected act.

For example, `myFunc` runs on `go1.x` runtime and once it has tried to deploy the new version according to the following `function.json`:

```json
{
  "FunctionName": "myfunc",
  "MemorySize": 128,
  "Role": "arn:aws:iam::XXXXXXXXXXXX:role/__ROLE__",
  "Architectures": ["arm64"],
  "PackageType": "Image",
  "Code": {
    "ImageUri": "__IMAGE_URI__"
  }
}
```

`lambroll deploy` said like the following:

```
2021/12/17 16:08:32 [info] lambroll v0.12.3
2021/12/17 16:08:32 [info] starting deploy function myfunc
2021/12/17 16:08:33 [info] using docker image XXXXXXXXXXXX.dkr.ecr.__REGION__.amazonaws.com/__IMAGE__
2021/12/17 16:08:33 [info] creating function
2021/12/17 16:08:34 [info] State:Pending LastUpdateStatus:
2021/12/17 16:08:34 [info] waiting for LastUpdateStatus Successful
2021/12/17 16:08:35 [info] State:Pending LastUpdateStatus:
2021/12/17 16:08:35 [info] waiting for LastUpdateStatus Successful
2021/12/17 16:08:37 [info] State:Pending LastUpdateStatus:
2021/12/17 16:08:37 [info] waiting for LastUpdateStatus Successful
2021/12/17 16:08:42 [info] State:Pending LastUpdateStatus:
2021/12/17 16:08:42 [info] waiting for LastUpdateStatus Successful
2021/12/17 16:08:50 [info] State:Active LastUpdateStatus:Successful
2021/12/17 16:08:50 [info] deployed function version 10
2021/12/17 16:08:50 [info] creating alias set current to version 10
2021/12/17 16:08:50 [info] alias created
2021/12/17 16:08:50 [info] completed
```

I think this would be nicer if this fails under the situation...

### Apendix

```
$ lambroll version
lambroll v0.12.3
```

**Comment by fujiwara** [comment]
Thank you for reporting!

Lambda's UpdateFunctionCode API accepts a request that includes change PackageType, so the deployments are completed successfully. But these changes are not applied actually...

Add validations for change of PackageType by #206.
v0.12.6 released! https://github.com/fujiwara/lambroll/releases/tag/v0.12.6

**Comment by moznion** [comment]
I've confirmed the new behavior on my machine, perfect!
I appreciate your super quick support.
