### ISSUE TITLE
new version release?

### ISSUE THREAD

**Issue by Liooo** [fujiwara/lambroll#251]
Hello @fujiwara, is there a plan to release a new version anytime soon?
I'd love to use this feature: https://github.com/fujiwara/lambroll/pull/236

**Comment by fujiwara** [comment]
@Liooo https://github.com/fujiwara/lambroll/releases/tag/v0.13.0 released!!!

**Comment by Liooo** [comment]
@fujiwara 

thank you so much 🎉
