### ISSUE TITLE
lambroll deploy doesn't catch errors from lambda

### ISSUE THREAD

**Issue by lacolaco** [fujiwara/lambroll#290]
Thank you for your useful tool. I'd like to share an insight about codes that probably is better to be fixed.

Recently my team encountered an issue about deployment docker image to Lambda. The cause is something related to docker build, not to lambroll.
But strangely, in our workflow `lambroll deploy` was running successfully and seemed ok while the error happens.

After solving our issue, I've found the code that probably is the reason of the behavior.

https://github.com/fujiwara/lambroll/blob/dab5b17699cca6f419d8607733e9ecc86fdac443/deploy.go#L219-L232

This code catches all `awserr.Error`s at the first `if` statement but only `lambda.ErrCodeResourceConflictException` is handled. All other `awserr.Error` are ignored and go forward to the successful return.

I think the `switch` should have `default` clause and handle unexpected errors, or remove `else` from the if statement, to handle every `awserr.Error`s.

**Comment by fujiwara** [comment]
@lacolaco Thank you for reporting!
I've fixed this in https://github.com/fujiwara/lambroll/pull/289.

**Comment by lacolaco** [comment]
@fujiwara Thank you for the rapid fix!

**Comment by fujiwara** [comment]
v0.14.2 released! https://github.com/fujiwara/lambroll/releases/tag/v0.14.2
