### ISSUE TITLE
some command line options like "--alias" drifts on v1

### ISSUE THREAD

**Issue by miztch** [fujiwara/lambroll#357]
Once upgrading lambroll from v0.14.x to v1.0.0, I found that `lambroll deploy` with `--alias` fails with error.

```
$ lambroll version
lambroll v1.0.0
$ lambroll deploy --alias live --region $AWS_DEFAULT_REGION
2024/02/13 11:12:29 [error] FAILED. failed to parse args: unknown flag --alias, did you mean one of "--alias-name", "--alias-to-latest"?
```

This might have come to occur because of #315 (replacement of kingpin with Kong).
Also I found following drifts that may be the same between v0.14.7 and v1.0.0.

- on `lambroll init`
  - `--download` changes into `--download-zip`
- on `lambroll diff`
  - `--code` changes into `--code-sha-256`

If these changes are not intended (and if you think it needs to keep compatibility),  I would like to create a pull request to fix them same as b80f49e.  (fix for `--tfstate` and `--prefixed-tfstate`)

**Comment by fujiwara** [comment]
@miztch Thank you for the reporting!

I confirmed these flag names changed unintentionally between v0.14.7 and v1.0.0.

I'll check all of the flags from now. Please wait for a little.

**Comment by fujiwara** [comment]
I've checked all the flags in v0.14 and found three flags have different names against the auto-generated name from the attribute name.

```
InitOption.DownloadZip => download
DeployOption.AliasName => alias
DiffOption.CodeSha256 => code
```

These flags should be named by `name:"..."` struct tag.

@miztch I can fix this issue, but if you send a pull request, I'm pleased to do accept it.

**Comment by miztch** [comment]
@fujiwara Thanks for the quick response! I've opened a pull request #358, so could you have a look at?

**Comment by fujiwara** [comment]
@miztch Thank you!! v1.0.1 released!
https://github.com/fujiwara/lambroll/releases/tag/v1.0.1

**Comment by miztch** [comment]
@fujiwara How fast!
I've confirmed my deploy with `--alias` success with v1.0.1, so I will close this issue. Thanks for the approve!
