### ISSUE TITLE
Add `--alias` flag to `lambroll rollback`

### ISSUE THREAD

**Issue by MasatoshiTada8888** [fujiwara/lambroll#360]
We can specify an arbitrary alias name with `--alias` flag for `lambroll deploy` command.
However, we cannot specify an alias name for `lambroll rollback` command.
I think `lambroll rollback` command should have `--alias` flag.

**Comment by fujiwara** [comment]
@MasatoshiTada8888 Thank you!
v1.0.2 released! https://github.com/fujiwara/lambroll/releases/tag/v1.0.2
