### ISSUE TITLE
Add auto approve option (like `terraform apply -auto-approve`) to `lambroll init`

### ISSUE THREAD

**Issue by MasatoshiTada8888** [fujiwara/lambroll#376]
I use Terraform to create a Lambda function at first and thereafter use lambroll to deploy.
Therefore there are two files to have the state of the function (Terraform's xxx.tf and lambroll's function.json).
I'd like to use Terraform to maintain the state of the function.
So I run `lambroll init` every time before I run `lambroll deploy` to prevent overwriting the state of the function.
In this case, `lambroll init` asks me `Overwrite existing file .lambdaignore?` and `Overwrite existing file function.json?` and I have to enter `y` manually.
This means I cannot use lambroll in Continuous Deployment.
I need the auto approve option to use lambroll in CD.
I kindly request your consideration.

**Comment by fujiwara** [comment]
At first, `lambroll init` is intended once to create configuration files manually.
But I recognize this use case (calling `init` in CD processes). I'll add `lambroll init --force-overwrite` flag to force override existing files.
